function [beta_weak,beta_strong] = TBM_get_beta(M,theta,gamma)
%TBM_GET_THETA Summary of this function goes here
%   Detailed explanation goes here

lambda = sqrt( (M.^2-1).^2 - ...
               (3.*(1+(gamma-1)./2.*M.^2) ...
                 .*(1+(gamma+1)./2.*M.^2) ...
                 .*(tan(theta).^2)) );
chi = (1./lambda.^3) .* ...
      ( (M.^2-1).^3 - ...
        (9.*(1+(gamma-1)./2.*M.^2) ...
          .*(1+(gamma-1)./2.*M.^2+(gamma+1)./4.*M.^4) ...
          .*(tan(theta).^2)) );

% weak shock
delta = 1;
beta_weak = atan( ( M.^2 - 1 + 2.*lambda.*cos((4.*pi.*delta+acos(chi))./3) ) ./ ...
                  ( 3.*(1+(gamma-1)./2.*M.^2).*tan(theta) ) );
              
% strong shock
delta = 0;
beta_strong = atan( ( M.^2 - 1 + 2.*lambda.*cos((4.*pi.*delta+acos(chi))./3) ) ./ ...
                    ( 3.*(1+(gamma-1)./2.*M.^2).*tan(theta) ) );

end

